spring.application.name=turbo-az-bot

spring.datasource.url=jdbc:mysql://localhost:3306/turboazbot?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update

telegram.bot.username=Turboaz3_bot
telegram.bot.token=8454907934:AAElOAf1o6Cagk745u2saG1wtI5wV6QopOI





