spring.application.name=turbo-az-bot

spring.datasource.url=jdbc:mysql://localhost:3306/turboazbot?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update

telegram.bot.username=Turboaz_Helper1_bot
telegram.bot.token=8259579588:AAG5d2z3ICh78o22Ie_3FYb9l7GO63zE0xQ





